LR-17 공통 클래스 세팅
TzurroAndTheGuys/leisurero-server pull request #2
Opened 2024-10-26 07:35 UTC by goyounha11

2024-10-27 09:31 UTC, Hejow requested changes
작성하시느라 고생 많으셨습니당!!

2024-10-27 09:31 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/extension/RepositoryExtension.kt
> +fun <T, ID : Any> CrudRepository<T, ID>.findByIdOrThrow(id: ID, errorCode: ErrorCode): T = findById(id).orElseThrow {
다음은 어떠신가용??
```suggestion
fun <T, ID> CrudRepository<T, ID>.findByIdOrThrow(id: ID, errorCode: () -> ErrorCode) =
  findByIdOrNull(id) ?: throw KotechException(errorCode())
```

2024-10-27 09:31 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/response/ApiResult.kt
> +class ApiResult<T>(
`@JsonInclude(JsonInclude.Include.NON_NULL)` 을 붙여서 null 값은 안내려버리는건 오똔가용??

2024-10-27 09:31 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +  var code: String,
이번에는 코드 관리 안하는건 어떤가용?? 코드 관리하니까 유지보수의 대상이 되는 것 같아서 고민입니다..!

클라우드 서비스처럼 외부에 제공점이 많은 경우는 코드를 알려줘서 관리할 필요가 있는 것 같은데 저희는 크게 필요한지 필요성을 못 느꼈습니다

2024-10-27 09:31 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +class LeisureroException(var errorCode: ErrorCode) : RuntimeException()
선언되고 던져지고 끝이니 data class로 선언하는건 어떤가요??
그리고 message 혹은 throwable이 필요에 따라서 변경될 수 있으니까 그 부분도 같이 제공하면 좋을 것 같아요!

2024-10-27 09:31 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/response/ApiResult.kt
> +      return ApiResult(errorCode.code, errorCode.message, null)
코들린을 사용하니까 default값을 줘서 null을 빼는건 어떠신가요??

2024-10-27 09:31 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +  SUCCESS_NORMAL("S000", "성공"),
성공인데 ErrorCode에 있는게 조금 어색하지 않나용 ?.?

2024-10-27 09:31 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/response/Result.kt
> +    Assert.notNull(errorCode, "Parameter `exceptionCode` must not be null")
null을 입력받을 수 있다면 (`errorCode: ErrorCode?`) assertion이 괜찮을 것 같은데 아니라서 빼는게 좋을 것 같아요!

2024-10-27 09:31 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/response/Result.kt
> +  }
다음은 어떤가용??

```suggestion
  fun error(leisureroException: LeisureroException) = error(leisureroException.errorCode)
```

2024-10-27 09:31 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/response/Result.kt
`ResponseEntity`를 쓴다면 저는 정적 팩토리 메서드를 적극 활용하는게 좋을 것 같은데 어떤가요??

그리고 object인 `Result`에서 정적 팩토리로 생성했을 때는 일반적으로 `Result`가 리턴되거나 관계가 있는 인스턴스가 리턴될거라는 예상이 들어요.
그런데 `ResponseEntity`로 감싸진 `ApiResult`를 리턴하는게, `ApiResult`에서 충분하게 제어해줄 수 있는 부분을 불필요하게 한번 더 wrapping하는 기분이 들어서 안 쓰는 방향으로 가보시는건 어떤가요??

2024-10-27 10:07 UTC, goyounha11 commented on build.gradle.kts
> +  implementation("io.github.microutils:kotlin-logging:3.0.5")
https://velog.io/@glencode/kotlin-logging%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-%ED%9A%A8%EA%B3%BC%EC%A0%81%EC%9C%BC%EB%A1%9C-%EB%A1%9C%EA%B9%85%ED%95%98%EA%B8%B0

이거 보고 참고했습니다~!

2024-10-27 10:08 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/exception/ApiAdvice.kt
> +  @ExceptionHandler(Exception::class)
딱히 이유는 없고 최상위 익셉션이라 어떤 익셉션이든 잡히게 하기 위해서 입니다~! RuntimeException으로 해도 문제되는 부분은 없을 것 같습니다~

2024-10-27 10:09 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/extension/RepositoryExtension.kt
> +package com.leisurero.common.extension
좋습니다~

2024-10-27 10:13 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/response/ApiResult.kt
> +class ApiResult<T>(
일단 의도는 null인 경우도 data : null 로 나가게하는게 의도긴 했습니다. 
왜냐면 사용자입장에서 어떤건 data가 존재하고 어떤건 data가 존재하지 않는다면 다소 혼란스러울 수 있겠다고 생각하는데 어떻게 생각하시나요?

2024-10-27 10:17 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/response/Result.kt
ApiResult에서는 그럼 of가 아닌 created, ok, error 이런 함수들이 컴패니언 오브젝트로 관리하자라는 의미 맞을까요?

2024-10-27 10:21 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/extension/RepositoryExtension.kt
> +package com.leisurero.common.extension
반영완료~

2024-10-27 10:21 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/exception/ApiAdvice.kt
> +  @ExceptionHandler(Exception::class)
반영완료~

2024-10-27 10:21 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/extension/RepositoryExtension.kt
> +fun <T, ID : Any> CrudRepository<T, ID>.findByIdOrThrow(id: ID, errorCode: ErrorCode): T = findById(id).orElseThrow {
반영완료~

2024-10-27 10:23 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +class LeisureroException(var errorCode: ErrorCode) : RuntimeException()
의도하신게 맞는지 체크 부탁드립니다~

2024-10-27 10:24 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/response/ApiResult.kt
> +      return ApiResult(errorCode.code, errorCode.message, null)
반영완료~

2024-10-27 10:25 UTC, Hejow commented on build.gradle.kts
> +  implementation("io.github.microutils:kotlin-logging:3.0.5")
해당 글에서 언급한 sl4j 이슈는 없고 저 wrapping 라이브러리를 사용하지 않아도 string template을 사용할 수도 있어요! 

logger를 전역(같은 파일 안에)으로 선언해버리면 해당 파일이 **클래스가 아닌 파일로 분류**되는 경우가 있어서 오히려 찾는데 불편해서 그냥 의존성을 추가하지 않는 방향은 어떤가요??

2024-10-27 10:26 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +  SUCCESS_NORMAL("S000", "성공"),
저도 좀 느끼는데 
![image](https://github.com/user-attachments/assets/c6866627-39b4-4ec7-8569-7268f2a6fae0)
이런식도 생각해봤는데 관리포인트만 늘어나는 것 같아서요~! ErrorCode라는 이름 보다는 어떤 적절한 이름을 사용하는게 나을까요?

2024-10-27 10:27 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/response/ApiResult.kt
> +class ApiResult<T>(
프론트 엔지니어는 **API 문서를 보고 어떤 값이 넘어오는지 알고있기 때문**에 null으로 인해서 혼선을 가질 일이 없을거라고 생각합니다!

2024-10-27 10:27 UTC, goyounha11 commented on build.gradle.kts
> +  implementation("io.github.microutils:kotlin-logging:3.0.5")
그러시져~

2024-10-27 10:29 UTC, goyounha11 commented on build.gradle.kts
> +  implementation("io.github.microutils:kotlin-logging:3.0.5")
반영완료~

2024-10-27 10:30 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/response/ApiResult.kt
> +class ApiResult<T>(
아하~ 넵 일단 희조님 의견대로 가시져~!

2024-10-27 10:30 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/response/ApiResult.kt
> +class ApiResult<T>(
반영완료~

2024-10-27 10:31 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/response/Result.kt
> +    Assert.notNull(errorCode, "Parameter `exceptionCode` must not be null")
반영완료~

2024-10-27 10:32 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +  var code: String,
[7:19](https://w1715926293-d9t887058.slack.com/archives/C07SW89Q88L/p1730024355355729)
아 잠시 제가 폰으로봐서 이해를 잘못햇었네영
message와 data로만 하는것어떠냐 이런거졍

2024-10-27 10:33 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +  SUCCESS_NORMAL("S000", "성공"),
우선 200을 내리면 성공했다는 것이므로 상태 코드에 맞춰서 내리는게 낫다는 생각입니다!
그리고 ErrorCode가 변화하기 보다는 그냥 성공에 대한 값을 빼는게 나을 것 같단 생각입니다!

나아가 예외 응답 객체도 분리하는게 나을 것 같다는 생각이 듭니다.
지금 구조는 예외 핸들러와 controller에서 같은 응답으로 묶고자 ReponsEntity<ApiResult>> 같은 코드가 등장했는데,
예외 핸들러가 아니면 과연 예외 응답에 대해서 알 필요가 있는가? 라는 생각이 들어요!
직접적으로 Controller가 예외를 던지는 경우도 존재하지 않구요!

ErrorResponse와 ApiResult로 분리하면 이런 관심사의 분리도 똑 떨어지고 ErrorCode가 가지는 성공 상태도 분리할 수 있을거라고 생각합니다!

2024-10-27 10:38 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/response/Result.kt
Erorr는 [앞선 의견](https://github.com/TzurroAndTheGuys/leisurero-server/pull/2#discussion_r1818057129)에 따라서 관리하고 나머지는 companion으로 처리하는건 어떤가용?

2024-10-27 10:39 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/extension/repository/RepositoryExtension.kt
> +package com.leisurero.common.extension.repository
이거 반대가 되는게 낫지 않을까요?? 그리고 repository말고 common이니까 JPA가 더 자연스러운 것 같습니다

```
package com.leisurero.common.jpa.extension
```

2024-10-27 10:47 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +  SUCCESS_NORMAL("S000", "성공"),
이해했습니다~! 
근데 제가 겪었던 환경과 지금 제가 생각하는건 핸들링된 오류는 성공이라고 본다는 것인데요.
이부분을 클라잘못일경우 4xx, 서버오류일경우 5xx 이런식으로 세세하게 해주자는 의견이시지요?

2024-10-27 10:49 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +  SUCCESS_NORMAL("S000", "성공"),
넵넵!

2024-10-27 10:50 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +  var code: String,
넵 아니면 다른 유의미한 값을 추가해줘도 좋을 것 같아요! 제가 건의한 방법대로라면 httpstatus를 가지고 있어도 무방하겠더라구요!

code는 저번에 100몇개 있는데 중간에 하나 빼니까 바로 순서 맞춰주기도 애매하고 안해주기도 애매했어서 따흑~

2024-10-27 10:53 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +  var code: String,
따흑~~ 저도 항상 비슷한 문제를 겪었던것같습니다.
좋아용 코드빼구 가보죠!

2024-10-27 12:49 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +class LeisureroException(var errorCode: ErrorCode) : RuntimeException()
[baf4320](https://github.com/TzurroAndTheGuys/leisurero-server/pull/2/commits/baf4320acf935e2a50336d60f671b93eeecb5cd9)에서 message는 아무것도 안 넣으면 errorCode의 message 값을 쓰게 하면 좋을 것 같은데요??

2024-10-27 14:40 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/response/Result.kt
반영완료~

2024-10-27 14:40 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/extension/repository/RepositoryExtension.kt
> +package com.leisurero.common.extension.repository
반영완료~

2024-10-27 14:40 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/response/ApiResult.kt
> +    fun <T> of(errorCode: ErrorCode, data: T? = null): ApiResult<T> {
of가 없어졌으므로 자동 반영완료~

2024-10-28 06:46 UTC, Hejow approved these changes
슛~

2024-10-28 06:46 UTC, Hejow commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +) : RuntimeException(message ?: errorCode.message, cause)
message는 반드시 있으니까 nullable하게 열어주지 말고 다음과 같이 써보는건 어떨까용??
```suggestion
data class LeisureroException(
  var errorCode: ErrorCode,
  override val message: String = errorCode.message,
  override val cause: Throwable? = null,
) : RuntimeException(message, cause)
```

2024-10-28 07:05 UTC, goyounha11 commented on src/main/kotlin/com/leisurero/common/exception/LeisureroException.kt
> +) : RuntimeException(message ?: errorCode.message, cause)
완료우~ 어제 분명히 오류나서 뭐야!!하면서 차선책을 선택했었는데 저의 집중력 부족이었나보군요 ㅎ

2024-10-28 07:05 UTC, merged